
USE TIENDA_SHURIKEN_DB_COMICS
go

--DROP DATABASE TIENDA_SHURIKEN_DB

-- Tabla para Clientes
CREATE TABLE CLIENTES (
    DNICLIENTE VARCHAR(8) PRIMARY KEY,
    NOMCLIENTE NVARCHAR(50),
    APELLIDOCLIENTE NVARCHAR(50),
	CELULAR NUMERIC(9)
);
go

-- Tabla para Producto
CREATE TABLE PRODUCTO (
    CODPRODUC INT PRIMARY KEY,
	NOMBREPRODUC NVARCHAR(100),
	DESCRIPCION NVARCHAR(200),
	PRECIOCOMPRAPRUDUC DECIMAL(10, 2),
	PRECIOVENTAPRODUC DECIMAL (10,2),
    CATEGORIA NVARCHAR(50),
	EDITORIAL NVARCHAR(20), 
	ABREVIATURA NVARCHAR(10),
	ESTADO NVARCHAR(10),
	FECHAVENTA DATETIME,
);
go

CREATE TABLE EMPRESA (
    IDEMPRESA INT IDENTITY(1,1) PRIMARY KEY,
    RUCEMPRESARIAL VARCHAR(11),
    NOMEMPRESA NVARCHAR(100),
    DIRECCIONEMP NVARCHAR(100),
    NUMEMPRESA NUMERIC(9),
    CORREOEMP VARCHAR(100),
    LOGO VARBINARY(MAX),
    CONSTRAINT CHK_CORREOEMP_EMAIL CHECK (CORREOEMP LIKE '%_@%.%')
);
go

-- Tabla para Usuario con la columna NOMBREUSUARIO como clave primaria
CREATE TABLE USUARIO (
    NOMBREUSUARIO NVARCHAR(50) ,
    DNI NUMERIC(8)PRIMARY KEY,
    CONTRASEÑA NVARCHAR(50),
    RANGO NVARCHAR(20),
    EMPRESAID VARCHAR(11),
	--FOREIGN KEY (EMPRESAID) REFERENCES EMPRESA (RUCEMPRESARIAL)
);
go

CREATE TABLE COMPROBANTE (
    IDCOMPROBANTE NUMERIC(11),
    TIPOCOMPROBANTE VARCHAR(20), -- boleta, factura, nota de pedido
	DETALLES NVARCHAR(200),
	MONTO DECIMAL(10,2),
    FECHA DATETIME,
    DNICLIENTE NVARCHAR(8)
);
go

CREATE TABLE BOLETA(
	IDBOLETA NUMERIC(11)
	);
CREATE TABLE FACTURA(
	IDFACTURA NUMERIC(11)
	);
CREATE TABLE NOTADEPEDIDO(
	IDNOTADEPEDIDO NUMERIC(11)
	);
go

	INSERT INTO BOLETA (IDBOLETA)
VALUES (1000000000);
go
	INSERT INTO FACTURA(IDFACTURA)
VALUES (1000000000);
go
	INSERT INTO NOTADEPEDIDO(IDNOTADEPEDIDO)
VALUES (1000000000);
go

CREATE TABLE EGRESOS(
    IDEGRESO INT IDENTITY(1,1) PRIMARY KEY,
    FECHAEMISION DATETIME,
    CANTIDAD DECIMAL(10,2),
    DESCRIPCION NVARCHAR(100)
	);
go

CREATE TABLE INGRESOS(
	IDINGRESOS NUMERIC(11),
	--FECHAEMISION PARA EL BURRO QUE LO ESCRIBIÓ RICARDO BALBOA :V
	FECHAEMISION DATETIME,
	CANTIDAD DECIMAL(10,2),
	GANANCIA DECIMAL(10,2),
	TIPO NVARCHAR(10),
	METODO NVARCHAR(20)
	);
go

CREATE TABLE CAJA(
	IDCAJA INT IDENTITY(1,1) PRIMARY KEY,
	FECHA DATETIME,
	CANTIDAD DECIMAL(10,2),
	USUARIO NVARCHAR(20)
	);
go

-- Insertar un ejemplo de usuario
INSERT INTO USUARIO (NOMBREUSUARIO, DNI, CONTRASEÑA, RANGO)
VALUES ('RICARDO', '75629247', 'SHURIKEN', 'SUPERADMIN' );
go
INSERT INTO USUARIO (NOMBREUSUARIO, DNI, CONTRASEÑA, RANGO)
VALUES ('RAY', '00000000', 'SHURIKEN', 'ADMIN' );



